# Site settings
title: 준토
url: "https://ji-junhyuk.github.io"
baseurl: ""
description: >
    준토 블로그
# My information
email: takeoutmoneywallet@gmail.com
author: 준토
profile: 유물론자
twitter_username: 
github_username: ji-junhyuk
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: 
  shortname: 
utterances:
  repo: ji-junhyuk/ji-junhyuk.github.io
  issue-term: pathname
  label: Comment
  branch: main

google_analytics:
  ua: G-RK3M0SSQ6G

google_adsense:
  client: ca-pub-3675948545737694

blame: "https://github.com/ji-junhyuk/ji-junhyuk.github.io/blame/main/_wiki"
edit: "https://github.com/ji-junhyuk/ji-junhyuk.github.io/edit/main/_wiki"
issue: "https://github.com/ji-junhyuk/ji-junhyuk.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
